name: Transition to in review

on: 
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest
    name: Transition to in review
    if: ${{ !github.event.pull_request.draft }}
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    
    - name: Find in PR body
      id: find
      uses: atlassian/gajira-find-issue-key@master
      with:
       string: ${{ github.event.pull_request.body }}

    - name: Transition issue
      uses: atlassian/gajira-transition@master
      with:
        issue: ${{ steps.find.outputs.issue }}
        transition: "PR Created"

    - name: Comment on issue
      uses: atlassian/gajira-comment@master
      with:
       issue: ${{ steps.find.outputs.issue }}
       comment: ${{ github.event.pull_request.html_url }}